<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CgShop.Infrastructure\CgShop.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
